version: '3.4'
services:
  body-parser:
    build: .
    image: go-body-parser:1.0
    container_name : container-body-parser
    volumes:
      - type: bind
        source: ${CONFIGURES_DIRECTORY}
        target: /app/configures
    # ports:
    #   - "5000:${APP_PORT}"
    expose  :
      - "80"
    
networks: 
  site1 : 
    external: 
      name : proxy_middleware_net