version: '3.9'
services:
  single-middleware:
    networks: 
      proxy_middleware_net:  
    build: .
    image: go-single-middleware:1.0
    container_name: container-single-middleware
    volumes:
      - type: bind
        source: ../configures
        target: /app/configures
    # ports:
    #   - "5000:${APP_PORT}"
    expose:
      - "80"
  
    
networks: 
  default:
  proxy_middleware_net:
    external: true